### ISSUE TITLE
Changes to Listing NEPA Milestones

### ISSUE THREAD

**Issue by JJediny** [DOE-NEPA/mapwarper#2]
- [x] Change title to "NEPA Milestones"
- [x] Link back to Parent Page with "{{Document #}}{{Title}}"
- [x] Change Date to render to M/DD/YYYY
- [x] Change "View Entire Milestone" to "View"
- [x] Change "Add NEPA Milestone" to "Add Milestone" and render as a Bootstrap Button
  ![image](https://cloud.githubusercontent.com/assets/6350035/6100805/f8c64d82-afe4-11e4-8d09-a56a4af3ba1b.png)

**Comment by eisemann** [comment]
All checked
